Update README.md
deeplearningunb/pneumonia-diagnose pull request #22
Opened 2019-12-06 18:27 UTC by ErickGiffoni

this solves #21

2019-12-06 18:28 UTC, ErickGiffoni commented
@gabrielziegler3 
@davialvb 
deem uma olhada

2019-12-06 18:38 UTC, fernand0aguilar commented on README.md
> +|Fernando Aguilar|@fernand0aguilar|-|
fernando.aguilar@hotmail.com.br

2019-12-06 18:38 UTC, frclba approved these changes

2019-12-06 18:40 UTC, frclba requested changes

2019-12-06 18:40 UTC, fernand0aguilar commented on README.md
> +|Gabriel Ziegler|@gabrielziegler3|-|
gabrielziegler3@gmail.com

2019-12-06 18:40 UTC, fernand0aguilar commented on README.md
> +|Davi Alves|@davialvb|-|
davialvb@gmail.com

2019-12-07 01:09 UTC, ErickGiffoni commented
ja vou resolver

2019-12-07 01:12 UTC, ErickGiffoni commented on README.md
> +|Davi Alves|@davialvb|-|
resolvido

2019-12-07 01:13 UTC, ErickGiffoni commented on README.md
> +|Gabriel Ziegler|@gabrielziegler3|-|
resolvido

2019-12-07 01:13 UTC, ErickGiffoni commented on README.md
> +|Fernando Aguilar|@fernand0aguilar|-|
resolvido

2019-12-07 01:13 UTC, ErickGiffoni commented
tudo ok

2019-12-07 11:07 UTC, merged